/* imagespec-editor/profiles/gicisky.js */
window.ImagespecEditorProfile = {
  id: 'gicisky',
  title: 'Gicisky Layout Editor',
  action: 'gicisky.write',
  editorVersion: '260804',
  defaultFont: '',
  fontDefaultKeys: ['text', 'multiline', 'new_multiline', 'diagram', 'plot'],
  qrDefaultData: 'https://home-assistant.io',
  excludeElements: ['new_multiline'],
  multilineDelimiterRequired: true,
  canvas: {
    mode: 'preset', // deviceSelect + rotation swaps W/H
    rotationAffectsCanvas: true,
    defaultWidth: 296,
    defaultHeight: 128,
  },
  yaml: {
    emitWidthHeight: false,
    emitDensity: false,
  },
  toolbar: [
    { type: 'text', label: '📝 Text' },
    { type: 'line', label: '━ Line' },
    { type: 'rectangle', label: '▭ Rect' },
    { type: 'circle', label: '◯ Circle' },
    { type: 'ellipse', label: '⬮ Ellipse' },
    { type: 'icon', label: '★ Icon' },
    { type: 'dlimg', label: '🖼 Image' },
    { type: 'qrcode', label: '⊞ QR' },
    { type: 'barcode', label: '⊞ Barcode' },
    { type: 'progress_bar', label: '▰ Progress' },
    { type: 'multiline', label: '≡ Multi' },
    { type: 'rectangle_pattern', label: '⊞ Pattern' },
    { type: 'diagram', label: '📊 Diagram' },
    { type: 'plot', label: '📈 Plot' },
    { type: 'battery', label: '🔋 Battery' },
    { type: 'gauge', label: '◔ Gauge' },
    { type: 'pie', label: '🥧 Pie' },
    { type: 'sparkline', label: '〰 Spark' },
    { type: 'text_fit', label: '📐 TextFit' },
    { type: 'row', label: '↔ Row' },
    { type: 'column', label: '↕ Column' },
  ],
};
