/* imagespec-editor/profiles/niimbot.js */
window.ImagespecEditorProfile = {
  id: 'niimbot',
  title: 'Niimbot Layout Editor',
  action: 'niimbot.print',
  editorVersion: '260804',
  defaultFont: 'ppb.ttf',
  fontDefaultKeys: ['text', 'multiline', 'new_multiline', 'diagram', 'plot'],
  qrDefaultData: 'https://example.com',
  excludeElements: [],
  multilineDelimiterRequired: false,
  canvas: {
    mode: 'freeform', // width/height/density inputs
    rotationAffectsCanvas: false,
    defaultWidth: 400,
    defaultHeight: 240,
  },
  yaml: {
    emitWidthHeight: true,
    emitDensity: true,
  },
  toolbar: [
    { type: 'text', label: '📝 Text' },
    { type: 'multiline', label: '≡ Multi' },
    { type: 'new_multiline', label: '≡ NewMulti' },
    { type: 'line', label: '━ Line' },
    { type: 'rectangle', label: '▭ Rect' },
    { type: 'circle', label: '◯ Circle' },
    { type: 'ellipse', label: '⬮ Ellipse' },
    { type: 'icon', label: '★ Icon' },
    { type: 'dlimg', label: '🖼 Image' },
    { type: 'qrcode', label: '⊞ QR' },
    { type: 'barcode', label: '⊞ Barcode' },
    { type: 'progress_bar', label: '▰ Progress' },
    { type: 'rectangle_pattern', label: '⊞ Pattern' },
    { type: 'diagram', label: '📊 Diagram' },
    { type: 'plot', label: '📈 Plot' },
    { type: 'battery', label: '🔋 Battery' },
    { type: 'gauge', label: '◔ Gauge' },
    { type: 'pie', label: '🥧 Pie' },
    { type: 'sparkline', label: '〰 Spark' },
    { type: 'text_fit', label: '📐 TextFit' },
    { type: 'row', label: '↔ Row' },
    { type: 'column', label: '↕ Column' },
  ],
};
